import prisma from '../../lib/prisma';
import { NotFoundError } from '../../common/utils/apiError';

export class AgreementTemplatesService {
  /**
   * Retrieves all agreement templates with basic metadata and scheme name.
   */
  static async getAllTemplates() {
    try {
      const templates = await prisma.agreementTemplate.findMany({
        include: {
          scheme: {
            select: {
              name: true,
              code: true,
            }
          },
          parts: {
            include: {
              sections: {
                include: {
                  clauses: true
                }
              }
            }
          }
        },
        orderBy: { updatedAt: 'desc' }
      });

      return templates.map((t: any) => ({
        ...t,
        schemeName: t.scheme?.name || 'N/A'
      }));
    } catch (error: any) {
      console.error('Error in getAllTemplates:', error);
      throw error;
    }
  }

  /**
   * Retrieves a full template with all its nested Parts -> Sections -> Clauses.
   */
  static async getTemplateById(id: string) {
    const template = await prisma.agreementTemplate.findUnique({
      where: { id },
      include: {
        scheme: true,
        parts: {
          include: {
            sections: {
              include: {
                clauses: {
                  orderBy: { order: 'asc' }
                }
              },
              orderBy: { order: 'asc' }
            }
          },
          orderBy: { order: 'asc' }
        }
      }
    });

    if (!template) throw new NotFoundError('Agreement template not found');
    
    return {
      ...template,
      schemeName: (template as any).scheme?.name || 'N/A'
    };
  }

  /**
   * Creates a new template with nested structure.
   */
  static async createTemplate(data: any) {
    const { parts, ...rawTemplateData } = data;

    // Sanitize template data to only include valid Prisma model fields
    const templateData = {
      name: rawTemplateData.name,
      description: rawTemplateData.description,
      schemeId: rawTemplateData.schemeId,
      version: rawTemplateData.version || 1,
      status: (rawTemplateData.status || 'DRAFT').toUpperCase()
    };

    try {
      const template = await prisma.agreementTemplate.create({
        data: {
          ...templateData,
          parts: {
            create: parts?.map((part: any) => ({
              code: part.code,
              title: part.title,
              order: part.order,
              sections: {
                create: part.sections?.map((section: any) => ({
                  code: section.code,
                  title: section.title,
                  description: section.description,
                  isAutoGenerated: section.isAutoGenerated,
                  order: section.order,
                  clauses: {
                    create: section.clauses?.map((clause: any) => ({
                      title: clause.title,
                      content: clause.content,
                      order: clause.order,
                      isOptional: clause.isOptional,
                      version: 1
                    }))
                  }
                }))
              }
            }))
          }
        },
        include: {
          scheme: { select: { name: true } },
          parts: {
            include: {
              sections: {
                include: {
                  clauses: true
                }
              }
            }
          }
        }
      });

      return {
        ...template,
        schemeName: (template as any).scheme?.name || 'N/A'
      };
    } catch (error: any) {
      console.error('Error in createTemplate:', error);
      throw error;
    }
  }

  /**
   * Updates an existing template with nested structure.
   * For simplicity in DRAFT mode, it replaces all parts/sections/clauses.
   */
  static async updateTemplate(id: string, data: any) {
    const { parts, ...rawTemplateData } = data;

    // Sanitize template data to only include valid Prisma model fields
    const templateData = {
      name: rawTemplateData.name,
      description: rawTemplateData.description,
      schemeId: rawTemplateData.schemeId,
      version: rawTemplateData.version || 1,
      status: (rawTemplateData.status || 'DRAFT').toUpperCase()
    };

    try {
      // Use transaction to ensure data integrity
      return await prisma.$transaction(async (tx) => {
        // 1. Delete all existing parts (Cascade delete handles sections/clauses)
        await tx.agreementPart.deleteMany({ where: { templateId: id } });

        // 2. Update the root template
        const template = await tx.agreementTemplate.update({
          where: { id },
          data: {
            ...templateData,
            parts: {
              create: parts?.map((part: any) => ({
                code: part.code,
                title: part.title,
                order: part.order,
                sections: {
                  create: part.sections?.map((section: any) => ({
                    code: section.code,
                    title: section.title,
                    description: section.description,
                    isAutoGenerated: section.isAutoGenerated,
                    order: section.order,
                    clauses: {
                      create: section.clauses?.map((clause: any) => ({
                        title: clause.title,
                        content: clause.content,
                        order: clause.order,
                        isOptional: clause.isOptional,
                        version: clause.version || 1
                      }))
                    }
                  }))
                }
              }))
            }
          },
          include: {
            scheme: { select: { name: true } },
            parts: {
              include: {
                sections: {
                  include: {
                    clauses: true
                  }
                }
              }
            }
          }
        });

        return {
          ...template,
          schemeName: template.scheme?.name || 'N/A'
        };
      });
    } catch (error: any) {
      console.error('Error in updateTemplate:', error);
      throw error;
    }
  }

  /**
   * Deletes a template and its children (Cascade delete handled by Prisma).
   */
  static async deleteTemplate(id: string) {
    await this.getTemplateById(id);
    return await prisma.agreementTemplate.delete({
      where: { id }
    });
  }

  /**
   * Fetches a template and populates its placeholders with real data.
   */
  static async hydrateTemplate(templateId: string, variables: Record<string, string>) {
    const template = await this.getTemplateById(templateId);
    
    // Deep clone and replace placeholders in clause content
    const hydratedParts = template.parts.map((part: any) => ({
      ...part,
      sections: part.sections.map((section: any) => ({
        ...section,
        clauses: section.clauses.map((clause: any) => ({
          ...clause,
          content: this.replacePlaceholders(clause.content, variables)
        }))
      }))
    }));

    return { ...template, parts: hydratedParts };
  }

  /**
   * Helper function for regex-based placeholder replacement.
   */
  private static replacePlaceholders(content: string, variables: Record<string, string>) {
    // Matches {{placeholder_name}} or {{ placeholder_name }}
    return content.replace(/\{\{(.*?)\}\}/g, (match, key) => {
      const trimmedKey = key.trim();
      return variables[trimmedKey] !== undefined ? String(variables[trimmedKey]) : match;
    });
  }

  /**
   * Retrieves templates associated with a specific scheme.
   */
  static async getTemplatesByScheme(schemeId: string) {
    return await prisma.agreementTemplate.findMany({
      where: { schemeId },
      orderBy: { version: 'desc' }
    });
  }

  /**
   * Marks a template as active for a scheme.
   * Note: This usually involves marking others as archived.
   */
  static async setActiveTemplate(id: string) {
    const template = await this.getTemplateById(id);
    
    // Deactivate all others for this scheme
    await prisma.agreementTemplate.updateMany({
      where: { schemeId: template.schemeId },
      data: { status: 'ARCHIVED' }
    });

    // Activate this one
    const updated = await prisma.agreementTemplate.update({
      where: { id },
      data: { status: 'ACTIVE' },
      include: {
        scheme: { select: { name: true } },
        parts: {
          include: {
            sections: {
              include: {
                clauses: {
                  orderBy: { order: 'asc' }
                }
              },
              orderBy: { order: 'asc' }
            }
          },
          orderBy: { order: 'asc' }
        }
      }
    });

    return {
      ...updated,
      schemeName: (updated as any).scheme?.name || 'N/A'
    };
  }

  /**
   * Helper to extract linked applicationId from A1 metadata clause if it exists.
   * Searches all clauses in the A1 section for a JSON block containing applicationId.
   */
  static extractApplicationId(template: any): string | null {
    if (!template?.parts) return null;
    
    // 1. Find the metadata section (Part A, Section A1)
    const a1Section = template.parts
      .find((p: any) => p.code === 'A')
      ?.sections?.find((s: any) => s.code === 'A1');
    
    if (!a1Section?.clauses) return null;

    // 2. Look through all clauses in that section for a JSON payload containing applicationId
    for (const clause of a1Section.clauses) {
      if (!clause.content) continue;
      
      try {
        // Attempt to parse content as JSON
        const metadata = JSON.parse(clause.content);
        if (metadata && typeof metadata === 'object' && metadata.applicationId) {
          return metadata.applicationId;
        }
      } catch (e) {
        // Not a JSON clause, skip to next
        continue;
      }
    }

    return null;
  }
}
